apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: gameappv2 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gameappv2 
    spec:
      containers:
        - name: gameappv2 
          image: gameapp.azurecr.io/gameappv2
          ports:
          - containerPort: 8085