apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: mariohenriqegameapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mariohenriqegameapp 
    spec:
      containers:
        - name: mariohenriqegameapp 
          image: gameapp.azurecr.io/mariohenriqegameapp
          ports:
          - containerPort: 8085